### ISSUE TITLE
When performing 'awsmobile push' the process publishes the previous version, not the current.

### ISSUE THREAD

**Issue by jbarwick** [aws/aws-amplify#1173]
Do you want to request a feature or report a bug?

BUG

What is the current behavior?

when performing awsmobile 'push', the backend deploys the previous version.  Not the newly generated version. (cloud-api)

What is the expected behavior?

Regardless of the state of the backend service (cloud-api), the awsmobile 'push' command should publish the current zipped version.  Not the previous version.

Reproduce:

Step1) Go to your deployments S3 bucket.  Delete all the files.
Step2) Go to the .awsmobile/build-info and delete all the zip files in there.
Step3) Open mobile-hub-project.yml...don't change anything...just note the upload file name.
Step4) Run awsmobile 'push'.  It will zip up all of your backend api
Step5) Wait.  Wait.  Wait more...then note the ERROR statement. "cannot find artifiact upload/xxxxx"
Step6) notice that the upload/xxxxx was the name from the Step3 above
Step7) Open the mobile-hub-project.yml and note the uplaod name.  You will note the name is the same as in the .awsmobile/build-info directory.  Good!
Step8) Go to the .awsmobile/build-info folder and rename all the files to the OLD PREVIOUS version number.
Step9) type awsmobile 'push'...Voila!  Worked!

This tells me that the CloudFormation UPDATE command is being executed BEFORE the new mobile-hub-project.yml is being processed and updated in the MobileHub console.

An example of this is:

```
MacBook-Pro-4:cloud-api jbarwick$ awsmobile push

checking the backend contents
   building cloud-api
      zipping contact
      zipping help
      zipping info
      zipping team
   done
   generating backend project content
   done
backend build artifacts are saved at:
/Users/jbarwick/Development/Gorilla Pit/gorilla-tip-web/awsmobilejs/.awsmobile/backend-build

preparing for backend project update: gorilla-tip-web
   uploading help-20180704215912.zip
   uploading info-20180704215912.zip
   uploading team-20180704215912.zip
   uploading contact-20180704215912.zip
   upload Successful  info-20180704215912.zip
   upload Successful  team-20180704215912.zip
   upload Successful  contact-20180704215912.zip
   upload Successful  help-20180704215912.zip
done

updating backend project: gorilla-tip-web
Failed to update project gorilla-tip-web
{ BadRequestException: Unable to find build artifact uploads/contact-20180704213422.zip in S3 bucket gorillatipweb-deployments-mobilehub-417008146 for API function contact
    at Object.extractError (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Unable to find build artifact uploads/contact-20180704213422.zip in S3 bucket gorillatipweb-deployments-mobilehub-417008146 for API function contact',
  code: 'BadRequestException',
  time: 2018-07-04T14:00:39.213Z,
  requestId: '90534b94-7086-4819-84e6-31033a7ac33b',
  statusCode: 400,
  retryable: false,
  retryDelay: 2.573201891959176 }
```

**Comment by ChadElias** [comment]
+1 Just started running into this issue

**Comment by dhruvpratapsingh** [comment]
Any fix for this fellas?
