### ISSUE TITLE
aws-amplify fails to issue calls to sam-local

### ISSUE THREAD

**Issue by araleius** [aws/aws-amplify#359]
*Do you want to request a feature or report a bug?*

Issue regarding integration with `aws-sam-local`

*What is the current behavior?*

I'm using `aws-amplify` Auth and API modules to issue authenticated calls to my API Gateway API requiring aws_iam sigv4 authentication. In production this works fine (from my webapp to AWS), and it also works well using `aws-amplify` in my tests running against real API Gateway endpoints. However, when I run my tests locally against sam-local, the API requests fail before `sam-local` has a chance to record ever receiving the request. A `Network Error` is called out but the network is the local machine, and the issue does not reproduce with other client libraries.

*What is the expected behavior?*

I expect the calls to work properly, as they do against production endpoints, and as they do when I use a different node library to issue the test calls. If the requests made it as far as my code running in `sam-local` I'd be able to troubleshoot and reach out to the `sam-local` folks for assistance if required, but since they don't even seem to get as far as `sam-local` my starting point is the `aws-amplify` RestClient I'm at a loss and filing the question here. 

The previous version of my tests were using `request-promise-native` and have no issues running locally against `sam-local` (which does not enforce auth). Now that I've enabled auth for my APIs, I'd rather move to `aws-amplify` throughout and not have to rely on a different set of tests to test locally during development.  

*You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.*

I'm attaching a snippet of my test code and the DEBUG information logged by `aws-amplify`

**CODE**
```javascript
import Amplify, { API } from 'aws-amplify';

const amplifyConfig = {
  Auth: {
    region: process.env.AWS_REGION,
    identityPoolId: process.env.COGNITO_IDENTITY_POOL_ID,
    userPoolId: process.env.COGNITO_USER_POOL_ID,
    userPoolWebClientId: process.env.COGNITO_USER_POOL_CLIENT_ID
  },
  API: {
    region: process.env.AWS_REGION,
    endpoints: [
      {
        name: "DataService",
        endpoint: process.env.API_ENDPOINT
      }
    ]
  }
};

window.LOG_LEVEL = 'DEBUG';
Amplify.configure(amplifyConfig);

describe('Echo', () => {
  it('GET returns when no message', () => {
    expect.assertions(2);
    return API.get('DataService', '/echo')
    .then(response => {
      expect(response).toBeDefined();
      expect(response.metadata).toBeDefined();
    })
    .catch((error) => {
      console.log(error);
      expect(error).toBeNull();
    });
  });
});
```

**Logs**

```bash
  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:84
    [DEBUG] 27:06.432 AuthClass - changed from previous

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:100
    { '[DEBUG] 27:06.433 API - set credentials for api':
       { accessKeyId: 'FAKEJSVTFNAAJ55BWEKA',
         sessionToken: 'AgoGb32PYhluEJv//////////wEaCXVzLXdlc3QtMiKAAgqRu8rLF5dUJb97ZRB2FCP017xBVz8892hl+G1u3+McJJ7AnLQHt2zhU1nRmrG5AJeWphi23m+42NKEI+0RyM1TA9FQk828mojgWwJgF1Utf9v2iM6xt0eCkO7TsKoE8AviLLeBMMyCqbXdD1pfh0pyOsuCHb5UlMb2DzNCSJcgtrtigbPsdk+xtoxU9Q1WbdBZEJDmLcbWEzjSjEbYBKYIdV5+BeOuklWgzPa7A5UWPykBOPnMXhOFYXfk9Mj2LvtSI9DSswol0WxjBsdl8huO5fJkBQKA4wOFDdKLzaBnebCAWNnDeIyCbEccMochvMLKf53KTXpZf2rrGh0sNDgqgwYIgf//////////ARAAGgw1NjAyNTcyMTU0MzAiDHUgLGWdYJq9JeoltyrXBbXUcixg4LnZ6laovgkbqAlmxLiaVr/iSc02MNmDZxGkk4aQF9vY1T6461Q7gRVs1KIooVoqf4VuT2GBz6A4ySjqGlaQxCi1TByIRQXuR0qUPTyh91aTcpclDXIQ/Zraw6jMfw6VRNGS8O3uPnI7ykZTGvuHFsKm8D2s5OTHNILPyyIqOZHyrZqg4xpRwFmVW9DcwpQw7/LBUN3FuXRamEbsIUyXlqjDFQE0EeTAXL92ptbrNnHPFKAtX1ONN/+rP9IUM/1Ag2sQUlX6vilAdO+euxTrDrQnDLtw65Get8Ly/uczaf+lNpmO7Gs7u2wqDZbgW4kSW2Jsq9B3fsNfydaSvq1fO0b2KVb3N531EApDdSDTjH0cT0Jiixv1Bhpqtfb1M8MSqRrEbfZWYKdMdGLRyX9ZbOQhJcyCwSuOO0M3s++mcfSbGDijFUuhcSvBO4UE0TPp7DCDZWvlWbhnDCn1HEUgelEfQ/kCHjkM6rG3GrWa/MRNgExIREgzAlidLpDbTDIg6wYgm3w8kFlkW+7OLC9OCfr2fxxxIqG6iJwYmZuABj+bDOBXVVD9jeH0he523m6GyXsk6GIpNd9dhD/2MwZb8mTh4Z7s84Png8ujinlIQ1JTm+y//6PLY30pb57sWwIbs8weoCcLlE8hpShVfwKVgzZjsKCHMcBYRdcpmIiUO6+88tZlFlSR9VYhIRXxaxPPx1CcL7z62beYkx0xjl6oV1wUHK2bJPLf8ohiCqnMNNOVlfVqukn4BIUhp8ZdhYKUmVH1VyRJyssn80QxWU4WwpfsbmIY+Ld7zK/2omHchp61QsxzlRg8bZ0+4VMHMogGmNA6lz/G+RK3CS8kUW8YNO/h39VNZtbzw6t8f0G+7gzgNc/TD6WKj6nh/3oEb+dDYsVGX8xsFcmYTVDb+wKa3Pn40e8M3QNunTxWYNGVSGcaDJdxIEjfTDYdiXQglcywRLIwyunH1AU=',
         secretAccessKey: 'ofajt5D45tXaCtDcWCvOY6Nbu/UkhYR9bjHIQu4',
         identityId: 'us-west-2:0ba7d111-aaaa-9b99-88bb-98f16bdd21cf',
         authenticated: false } }

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:84
    [DEBUG] 27:06.435 RestClient - GET http://127.0.0.1:3000/echo

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:84
    [DEBUG] 27:06.436 Signer - GET
    /echo

    host:127.0.0.1:3000
    x-amz-date:20180224T232706Z
    x-amz-security-token:AgoGb32PYhluEJv//////////wEaCXVzLXdlc3QtMiKAAgqRu8rLF5dUJb97ZRB2FCP017xBVz8892hl+G1u3+McJJ7AnLQHt2zhU1nRmrG5AJeWphi23m+42NKEI+0RyM1TA9FQk828mojgWwJgF1Utf9v2iM6xt0eCkO7TsKoE8AviLLeBMMyCqbXdD1pfh0pyEwgCHb5UlMb2DzNCSJcgtrtigbPsdk+xtoxU9Q1WbdBZEJDmLcbWEzjSjEbYBKYIdV5+BeOuklWgzPa7A5UWPykBOPnMXhOFYXfk9Mj2LvtSI9DSswol0WxjBsdl8huO5fJkBQKA4wOFDdKLzaBnebCAWNnDeIyCbEccMochvMLKf53KTXpZf2rrGh0sNDgqgwYIgf//////////ARAAGgw1NjAyNTcyMTU0MzAiDHUgLGWdYJq9JeoltyrXBbXUcixg4LnZ6laovgkbqAlmxLiaVr/iSc02MNmDZxGkk4aQF9vY1T6461Q7gRVs1KIooVoqf4VuT2GBz6A4ySjqGlaQxCi1TByIRQXuR0qUPTyh91aTcpclDXIQ/Zraw6jMfw6VRNGS8O3uPnI7ykZTGvuHFsKm8D2s5OTHNILPyyIqOZHyrZqg4xpRwFmVW9DcwpQw7/LBUN3FuXRamEbsIUyXlqjDFQE0EeTAXL92ptbrNnHPFKAtX1ONN/+rP9IUM/1Ag2sQUlX6vilAdO+euxTrDrQnDLtw65Get8Ly/uczaf+lNpmO7Gs7u2wqDZbgW4kSW2Jsq9B3fsNfydaSvq1fO0b2KVb3N531EApDdSDTjH0cT0Jiixv1Bhpqtfb1M8MSqRrEbfZWYKdMdGLRyX9ZbOQhJcyCwSuOO0M3s++mcfSbGDijFUuhcSvBO4UE0TPp7DCDZWvlWbhnDCn1HEUgelEfQ/kCHjkM6rG3GrWa/MRNgExIREgzAlidLpDbTDIg6wYgm3w8kFlkW+7OLC9OCfr2fxxxIqG6iJwYmZuABj+bDOBXVVD9jeH0he523m6GyXsk6GIpNd9dhD/2MwZb8mTh4Z7s84Png8ujinlIQ1JTm+y//6PLY30pb57sWwIbs8weoCcLlE8hpShVfwKVgzZjsKCHMcBYRdcpmIiUO6+88tZlFlSR9VYhIRXxaxPPx1CcL7z62beYkx0xjl6oV1wUHK2bJPLf8ohiCqnMNNOVlfVqukn4BIUhp8ZdhYKUmVH1VyRJyssn80QxWU4WwpfsbmIY+Ld7zK/2omHchp61QsxzlRg8bZ0+4VMHMogGmNA6lz/G+RK3CS8kUW8YNO/h39VNZtbzw6t8f0G+7gzgNc/TD6WKj6nh/3oEb+dDYsVGX8xsFcmYTVDb+wKa3Pn40e8M3QNunTxWYNGVSGcaDJdxIEjfTDYdiXQglcywRLIwyunH1AU=

    host;x-amz-date;x-amz-security-token
    e3b0c44298fc1c149afbf4c8888fb92427ae41e5555b934ca495991b7852b855

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:90
    { '[DEBUG] 27:06.437 Signer': { service: 'execute-api', region: 'us-west-2' } }

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:100
    { '[DEBUG] 27:06.437 RestClient - Signed Request: ':
       { method: 'GET',
         url: 'http://127.0.0.1:3000/echo',
         host: '127.0.0.1:3000',
         path: '/echo',
         headers:
          { host: '127.0.0.1:3000',
            'x-amz-date': '20180224T232706Z',
            'X-Amz-Security-Token': 'AgoGb32PYhluEJv//////////wEaCXVzLXdlc3QtMiKAAgqRu8rLF5dUJb97ZRB2FCP017xBVz8892hl+G1u3+McJJ7AnLQHt2zhU1nRmrG5AJeWphi23m+42NKEI+0RyM1TA9FQk828mojgWwJgF1Utf9v2iM6xt0eCkO7TsKoE8AviLLeBMMyCqbXdD1pfh0pyEwgCHb5UlMb2DzNCSJcgtrtigbPsdk+xtoxU9Q1WbdBZEJDmLcbWEzjSjEbYBKYIdV5+BeOuklWgzPa7A5UWPykBOPnMXhOFYXfk9Mj2LvtSI9DSswol0WxjBsdl8huO5fJkBQKA4wOFDdKLzaBnebCAWNnDeIyCbEccMochvMLKf53KTXpZf2rrGh0sNDgqgwYIgf//////////ARAAGgw1NjAyNTcyMTU0MzAiDHUgLGWdYJq9JeoltyrXBbXUcixg4LnZ6laovgkbqAlmxLiaVr/iSc02MNmDZxGkk4aQF9vY1T6461Q7gRVs1KIooVoqf4VuT2GBz6A4ySjqGlaQxCi1TByIRQXuR0qUPTyh91aTcpclDXIQ/Zraw6jMfw6VRNGS8O3uPnI7ykZTGvuHFsKm8D2s5OTHNILPyyIqOZHyrZqg4xpRwFmVW9DcwpQw7/LBUN3FuXRamEbsIUyXlqjDFQE0EeTAXL92ptbrNnHPFKAtX1ONN/+rP9IUM/1Ag2sQUlX6vilAdO+euxTrDrQnDLtw65Get8Ly/uczaf+lNpmO7Gs7u2wqDZbgW4kSW2Jsq9B3fsNfydaSvq1fO0b2KVb3N531EApDdSDTjH0cT0Jiixv1Bhpqtfb1M8MSqRrEbfZWYKdMdGLRyX9ZbOQhJcyCwSuOO0M3s++mcfSbGDijFUuhcSvBO4UE0TPp7DCDZWvlWbhnDCn1HEUgelEfQ/kCHjkM6rG3GrWa/MRNgExIREgzAlidLpDbTDIg6wYgm3w8kFlkW+7OLC9OCfr2fxxxIqG6iJwYmZuABj+bDOBXVVD9jeH0he523m6GyXsk6GIpNd9dhD/2MwZb8mTh4Z7s84Png8ujinlIQ1JTm+y//6PLY30pb57sWwIbs8weoCcLlE8hpShVfwKVgzZjsKCHMcBYRdcpmIiUO6+88tZlFlSR9VYhIRXxaxPPx1CcL7z62beYkx0xjl6oV1wUHK2bJPLf8ohiCqnMNNOVlfVqukn4BIUhp8ZdhYKUmVH1VyRJyssn80QxWU4WwpfsbmIY+Ld7zK/2omHchp61QsxzlRg8bZ0+4VMHMogGmNA6lz/G+RK3CS8kUW8YNO/h39VNZtbzw6t8f0G+7gzgNc/TD6WKj6nh/3oEb+dDYsVGX8xsFcmYTVDb+wKa3Pn40e8M3QNunTxWYNGVSGcaDJdxIEjfTDYdiXQglcywRLIwyunH1AU=',
            Authorization: 'AWS4-HMAC-SHA256 Credential=FAKEJSHTFNRVR33BWEKA/20180224/us-west-2/execute-api/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=593f4ee9eeea934912db2ecd059a80b815fae1f625cf39dd98a22dd78a7a41ce' },
         data: null } }

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: Response for preflight has invalid HTTP status code 502
        at Object.dispatchError (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at EventEmitter.client.on.err (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:664:20)
        at emitOne (events.js:120:20)
        at EventEmitter.emit (events.js:210:7)
        at Request.preflightClient.on.resp (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:373:16)
        at emitOne (events.js:115:13)
        at Request.emit (events.js:210:7)
        at Request.onRequestResponse (/Users/myuser/mycode/node_modules/request/request.js:1068:10)
        at emitOne (events.js:115:13)
        at ClientRequest.emit (events.js:210:7) undefined

  console.log node_modules/aws-amplify/lib/Common/Logger/ConsoleLogger.js:90
    { '[DEBUG] 27:06.463 RestClient':
       { Error: Network Error
        at createError (/Users/myuser/mycode/node_modules/axios/lib/core/createError.js:16:15)
        at XMLHttpRequest.handleError (/Users/myuser/mycode/node_modules/axios/lib/adapters/xhr.js:87:14)
        at XMLHttpRequest.el.addEventListener.event (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
        at invokeEventListeners (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at XMLHttpRequestEventTargetImpl._dispatch (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at XMLHttpRequestEventTargetImpl.dispatchEvent (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at XMLHttpRequest.dispatchEvent (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at requestErrorSteps (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:132:7)
        at Object.dispatchError (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
        at EventEmitter.client.on.err (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:664:20)
        at emitOne (events.js:120:20)
        at EventEmitter.emit (events.js:210:7)
        at Request.preflightClient.on.resp (/Users/myuser/mycode/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:373:16)
        at emitOne (events.js:115:13)
        at Request.emit (events.js:210:7)
        at Request.onRequestResponse (/Users/myuser/mycode/node_modules/request/request.js:1068:10)
        at emitOne (events.js:115:13)
        at ClientRequest.emit (events.js:210:7)
        at HTTPParser.parserOnIncomingClient (_http_client.js:549:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
        at Socket.socketOnData (_http_client.js:438:20)
        at emitOne (events.js:115:13)
        at Socket.emit (events.js:210:7)
        at addChunk (_stream_readable.js:264:12)
        at readableAddChunk (_stream_readable.js:251:11)
        at Socket.Readable.push (_stream_readable.js:209:10)
        at TCP.onread (net.js:587:20)
         config:
          { adapter: [Function: xhrAdapter],
            transformRequest: [Object],
            transformResponse: [Object],
            timeout: 0,
            xsrfCookieName: 'XSRF-TOKEN',
            xsrfHeaderName: 'X-XSRF-TOKEN',
            maxContentLength: -1,
            validateStatus: [Function: validateStatus],
            headers: [Object],
            method: 'get',
            url: 'http://127.0.0.1:3000/echo',
            host: '127.0.0.1:3000',
            path: '/echo',
            data: null },
         request:
          XMLHttpRequest {
            upload: [Object],
            _registeredHandlers: [Object],
            _eventHandlers: [Object],
            [Symbol(flag)]: [Object],
            [Symbol(properties)]: [Object] },
         response: undefined } }
```

**Comment by mlabieniec** [comment]
It looks like your requests are hitting your local, but it looks like the preflight response is invalid i.e. CORS. Perhaps one of the local configurations needs to be updated? I.e. via the sam template

https://github.com/awslabs/serverless-application-model/issues/135
https://github.com/awslabs/serverless-application-model/issues/23

**Comment by araleius** [comment]
I see.

My SAM template has the CORS configuration in the inline swagger for my `AWS::Serverless::Api`, including the default responses with the appropriate headers. All works as expected in API Gateway, just not locally. 

Thanks for pointing the obvious (which I hadn't paid enough attention to): the failure is being thrown by the preflight requests, prior to the actual requests. Since the pre-flight requests are handled correctly in production by API Gateway but fail with the local `sam-local` container it seems this is something I need to bring to the attention of the `sam-local` folks.; they're better placed to understand if this is an issue with my configuration, a bug, or something they don't support at this time. 

Closing this issue.

**Comment by araleius** [comment]
I was able to reproduce the preflight 502 issues with the following `curl` command, pasting here for posterity (in case someone runs into a similar issue in the future):
```
curl -H "Origin: http://example.com" -X OPTIONS --verbose http://127.0.0.1:3000/echo
```

**Comment by swaminator** [comment]
@araleius: I'm a PM at AWS Mobile. Would love to connect with you offline to chat about what you're building. How can I reach you?

**Comment by araleius** [comment]
For anyone who runs into a similar issue in the near future (before the state of affairs changes) here's the summary of the root cause and my current solution/workaround:

**Root cause**

When `sam-local` doesn't respond to the preflight OPTION request, the subsequent request will never be issued and the call will simply fail with a 502. 

As discussed on [sam-local issue #23](https://github.com/awslabs/serverless-application-model/issues/23), `sam-local` does not play very well with SAM templates that use a `{proxy+}` API Gateway `AWS::Serverless::Api` because unlike real AWS, configuring an ANY event in the `AWS::Serverless::Function` hooked to the API is not sufficient to get *any and all* http methods (i.e. GET/PUT/.../OPTIONS) to be served by `sam-local`. 

**Workaround**

I used to have something like this in my template (just relevant bits), which worked without issues for my proxy API to lambda in production:

```
Resources:
  ApiGatewayApi
    Type: AWS::Serverless::Api
    # ... the proxy api definition with CORS configuration
  
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [!Ref 'ProjectId', !Ref 'Stage']]
      Handler: index.handler
      Runtime: nodejs6.10
      Role: !GetAtt LambdaFunctionRole.Arn
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
```

I later discovered due to [sam-local issue #23](https://github.com/awslabs/serverless-application-model/issues/23) ANY is not enough for `sam-local` to map the specific methods with the underlying lambda handler. I had to add placeholder events for GET and POST (the http methods I use at this time), like so:

```
        # (this follow the ANY method, above)
        ProxyApiGetGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
            RestApiId: !Ref ApiGatewayApi
        ProxyApiPostGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: POST
            RestApiId: !Ref ApiGatewayApi
```

I personally prefer to do this just locally when running `sam-local` (not in production because it would result in the creation of some unnecessary lambda permissions).

To address the issue I was facing when I opened this issue, I simply added an event for the OPTION method, like so:

```
        # (this follow the other events, above)
        ProxyApiOptionsGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
            RestApiId: !Ref ApiGatewayApi
```

Once I did this and restarted `sam-local` my curl command for OPTIONS started returning a 200, and my tests with `aws-amplify` completed successfully.
