### ISSUE TITLE
navigator is not defined error

### ISSUE THREAD

**Issue by praveshkhatana** [aws/aws-amplify#754]
I am trying to integrate it with latest **Nativescript-angular** and using "*[*nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify)**" plugin.

```
require("nativescript-nodeify");
var Amplify = require("aws-amplify");
Amplify.configure({
    Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab', 
    // REQUIRED - Amazon Cognito Region
        region: 'XX-XXXX-X', 
    // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'XX-XXXX-X_abcd1234',
    // OPTIONAL - Amazon Cognito Web Client ID
        userPoolWebClientId: 'XX-XXXX-X_abcd1234', 
    }
});
```
but getting this error when I try to call "**_Amplify.configure_**"
```
JS: ERROR Error: Uncaught (in promise): ReferenceError: navigator is not defined
JS: ReferenceError: navigator is not defined
JS:     at standardBrowserEnv (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/helpers/isURLSameOrigin.js:11:39)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/helpers/isURLSameOrigin.js:60:5)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/adapters/xhr.js:7:23)
JS:     at require (<anonymous>:1:266)
JS:     at getDefaultAdapter (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/defaults.js:20:15)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/defaults.js:29:12)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/core/Axios.js:3:16)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/lib/axios.js:5:13)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/axios/index.js:1:78)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.awsamplify/files/app/tns_modules/aws-amplify/lib/API/RestClient.js:70:15)
```

_"aws-amplify": "^0.3.3",
"nativescript-angular": "~5.3.0",
    "nativescript-nodeify": "^0.7.0",_

**Comment by praveshkhatana** [comment]
Change it to "**aws-amplify": "^0.2.9**" version and everything working fine now :)

Just getting few warning messages

**Comment by praveshkhatana** [comment]
Why you closed this issue? Latest version **"aws-amplify": "^0.3.3"** still has an issue.

**Comment by praveshkhatana** [comment]
@manueliglesias how to fix it

**Comment by heldr** [comment]
It only uses navigator to retrieve userAgent https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L828

You can mock it in node: 

```js
global.navigator = {
  userAgent: 'NodeJS'
};
```
